server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848         #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard控制台服务地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
      web-context-unify: false # controller层的方法对service层调用不认为是同一个根链路

      datasource:  # sentinel 持久化配置
        ds1:      # 自定义key 也可以叫做限流配置
          nacos:
            server-addr: localhost:8848   # nacos地址
            dataId: ${spring.application.name}  # 配置文件id
            groupId: DEFAULT_GROUP   # 配置文件分组
            data-type: json     # 配置文件类型
            rule-type: flow # com.alibaba.cloud.sentinel.datasource.RuleType  限流规则（熔断，流控，热点，授权）